# Generated by Django 2.2.16 on 2022-10-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Описание произведения'),
        ),
    ]
