# Generated by Django 2.2.16 on 2022-10-18 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20221018_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-4000), django.core.validators.MaxValueValidator(2022)], verbose_name='Год выпуска произведения'),
        ),
    ]
