# Generated by Django 2.2.16 on 2022-10-14 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20221013_1742'),
        ('reviews', '0006_auto_20221013_0936'),
    ]

    operations = [
    ]
