# Generated by Django 2.2.16 on 2022-10-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_auto_20221020_0936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория (жанр)', 'verbose_name_plural': 'Категории (жанры)'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Категория (жанр)', 'verbose_name_plural': 'Категории (жанры)'},
        ),
    ]
