# Generated by Django 2.2.16 on 2022-10-20 13:06

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_auto_20221020_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)], verbose_name='Год выпуска произведения'),
        ),
    ]
