# Generated by Django 2.2.16 on 2022-10-20 16:52

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_auto_20221020_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[reviews.models.validate_year], verbose_name='Год выпуска произведения'),
        ),
    ]
